---
title: "About"
---

Statio está desarrollado en el marco del proyecto "Desarrollo y validación de simuladores virtuales para fomentar el aprendizaje activo en el ámbito de la estadística y la investigación operativa", impulsado por el Departamento de Estadística e Investigación Operativa Aplicadas y Calidad ([**DEIOAC**](https://www.upv.es/entidades/DEIO/)) de la Universitat Politècnica de València ([**UPV**](https://www.upv.es/)). Está financiado por el Instituto de Ciencias de la Educación ([**ICE**](https://www.upv.es/entidades/ice/)) mediate la convocatoria de Proyectos de Innovación y Mejora Educativa 2025 (PIME/25-26/562).

## Participantes

-   [Javier Marín Morales (Coordinador)](https://www.upv.es/ficha-personal/jamarmo){target="_blank" rel="noopener"}
    -   Contacto: jamarmo\@upv.es
-   [Alberto Altozano Fernandez](https://www.upv.es/ficha-personal/aaltfer){target="_blank" rel="noopener"}
-   [Vicente Chirivella González](https://www.upv.es/ficha-personal/vchirive){target="_blank" rel="noopener"}
-   [Adrian Colomer Granero](https://www.upv.es/ficha-personal/adcogra){target="_blank" rel="noopener"}
-   [Fortunato Crespo Abril](https://www.upv.es/ficha-personal/fcrespo){target="_blank" rel="noopener"}
-   [Ana Maria Debon Aucejo](https://www.upv.es/ficha-personal/andeau){target="_blank" rel="noopener"}
-   [Julia Domingo Ajenjo](https://www.upv.es/ficha-personal/jdomaje){target="_blank" rel="noopener"}
-   [Vicent Giner Bosch](https://www.upv.es/ficha-personal/vigibos){target="_blank" rel="noopener"}
-   [David Hervas Marin](https://www.upv.es/ficha-personal/daherma){target="_blank" rel="noopener"}
-   [María Lorduy Alós](https://www.upv.es/ficha-personal/maloral){target="_blank" rel="noopener"}
-   [Joaquin Martinez Minaya](https://www.upv.es/ficha-personal/jmarmin){target="_blank" rel="noopener"}
-   [José Ramón Navarro Cerdan](https://www.upv.es/ficha-personal/jonacer){target="_blank" rel="noopener"}
-   [Francisco Sanchez Saez](https://www.upv.es/ficha-personal/FRASANSA){target="_blank" rel="noopener"}
-   [Manuel Zarzo Castelló](https://www.upv.es/ficha-personal/mazarcas){target="_blank" rel="noopener"}
